required = [
  # Utilities
  "github.com/onsi/ginkgo/ginkgo",
  "github.com/golang/mock/mockgen",

  # Transitive Forks
  "github.com/opencontainers/runc/libcontainer/system",
  "golang.org/x/net/context",
]

ignored = [
  "code.cloudfoundry.org/cli/cf/resources",
]

# App

[[constraint]]
  name = "code.cloudfoundry.org/cli"
  version = "=6.32.0"

[[constraint]]
  name = "github.com/fsnotify/fsevents"
  source = "https://github.com/elastic/fsevents.git"
  branch = "master"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/go-version"
  branch = "master"

[[constraint]]
  name = "github.com/kardianos/osext"
  branch = "master"

[[constraint]]
  name = "github.com/nu7hatch/gouuid"
  branch = "master"

[[override]]
  name = "github.com/sclevine/forge"
  source = "https://github.com/jkutner/forge"
  branch = "heroku"

# Test

[[constraint]]
  name = "github.com/onsi/ginkgo"
  branch = "master"

[[constraint]]
  name = "github.com/onsi/gomega"
  branch = "master"

[[constraint]]
  name = "github.com/golang/mock"
  branch = "master"

# Transitive Forks

[[constraint]]
  name = "github.com/opencontainers/runc"
  source = "https://github.com/docker/runc.git"

[[constraint]]
  name = "golang.org/x/net"
  source = "https://github.com/tonistiigi/net.git"
